[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
test = "contracts/test"
cache_path = "cache"
broadcast = "broadcast"
ffi = false
optimizer = true
optimizer_runs = 200
remappings = [
  "forge-std/=lib/forge-std/src/"
]
